name: Keep Render App Awake

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 2 minutes
  workflow_dispatch:        # Allows manual run from GitHub

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the Render app
        run: |
          curl -Is https://assignmentaiuserserver.onrender.com || true
